// 播放器自定义事件
export enum PlayerEvents {
  DESTROY = "destroy",
  SWITCHDEFINITIONSTART = "switchDefinitionStart",
  SWITCHDEFINITIONEND = "switchDefinitionEnd",
  ENTERBROWSERSCREEN = "enterBrowserScreen",
  EXITBROWSERSCREEN = "exitBrowserScreen",
  ENTERWEBSCREEN = "enterWebScreen",
  EXITWEBSCREEN = "exitWebScreen",
  SHOWCONTROLS = "showControls",
  HIDECONTROLS = "hideControls",
  RESIZE = "resize",
  KEYBOARD_RIGHT = "keyboardRight",
  KEYBOARD_LEFT = "keyboardLeft",
  KEYBOARD_UP = "keyboardUp",
  KEYBOARD_DOWN = "keyboardDown",
  KEYBOARD_SPACE = "keyboardSpace",
  PICTURE_IN_PICTURE_WINDOW_RESIZE = "pictureInPictureWindowResize",
  BEFORECOMPONENTSETUP = "beforeComponentSetup",
  AFTERCOMPONENTSETUP = "afterComponentSetup",
  BEFORECOMPONENTDESTROY = "beforeComponentDestroy",
  AFTERCOMPONENTDESTROY = "afterComponentDestroy",
  BEFOREPLUGINSETUP = "beforePluginSetup",
  AFTERPLUGINSETUP = "afterPluginSetup",
  BEFOREPLUGINDESTROY = "beforePluginDestroy",
  AFTERPLUGINDESTROY = "afterPluginDestroy",
  BEFORETECHSETUP = "beforeTechSetup",
  AFTERTECHSETUP = "afterTechSetup",
  BEFORETECHDESTROY = "beforeTechDestroy",
  AFTERTECHDESTROY = "afterTechDestroy",
  PLAYERERROR = "playerError",
  SHOWERROR = "showErrorMessage",
  HIDEERROR = "hideErrorMessage"
}

// video标签事件
export enum VideoEvents {
  ABORT = "abort",
  CANPLAY = "canplay",
  CANPLAYTHROUGH = "canplaythrough",
  DURATIONCHANGE = "durationchange",
  EMPTIED = "emptied",
  ENDED = "ended",
  ERROR = "error",
  LOADEDDATA = "loadeddata",
  LOADEDMETADATA = "loadedmetadata",
  LOADSTART = "loadstart",
  PAUSE = "pause",
  PLAY = "play",
  PLAYING = "playing",
  PROGRESS = "progress",
  RATECHANGE = "ratechange",
  SEEKED = "seeked",
  SEEKING = "seeking",
  STALLED = "stalled",
  SUSPEND = "suspend",
  TIMEUPDATE = "timeupdate",
  VOLUMECHANGE = "volumechange",
  WAITING = "waiting",
  ENTERPICTUREINPICTURE = "enterpictureinpicture",
  LEAVEPICTUREINPICTURE = "leavepictureinpicture"
}
